before_script:
  - export SERVICE_NAME=$(echo $CI_JOB_NAME | awk '{split($0,a,":");print a[1]}')
  - export IMAGE_FULL_NAME=${CI_REGISTRY_IMAGE}/$SERVICE_NAME:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}

stages:
  - install
  - build
  - preview
  - prod

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

aka:install:
  image: node:12.14.1
  stage: install
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  before_script:
    - yarn config set registry https://registry.npm.taobao.org -g
    - yarn config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g
  script:
    - node -v
    - yarn -v
    - yarn
    - yarn build
  only:
    - /^release.*$/

aka:build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  dependencies:
    - aka:install
  tags:
    - docker
  script:
    - docker login -u $CI_DEPLOY_SECRET_USER -p $CI_DEPLOY_SECRET_PWD $CI_REGISTRY
    - docker build --rm --pull -t "$IMAGE_FULL_NAME" .
    - docker push "$IMAGE_FULL_NAME"
  only:
    - /^release.*$/

aka:preview:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: preview
  when: manual
  dependencies: []
  tags:
    - deploy-pre
  script:
    - echo "deploy preview"
  only:
    - /^release.*$/

aka:prod:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: prod
  when: manual
  dependencies: []
  tags:
    - prod
  script:
    - echo "deploy prod"
  only:
    - /^release.*$/